# This is a basic workflow to help you get started with Actions

name: DOHip4

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  UpdateDOHip4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - run: |
          #sudo rm -f DOHip4.txt
          #ls
          sudo mkdir temp
          sudo sh DOH_database_script.sh temp
          sudo mv temp/DOHip4.txt DOHip4.txt
          sudo rm -rf temp
          #ls
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update IP List
          #commit_options: '--no-verify --signoff'